server:
  port: 8005
spring:
  application:
    name: kitty-consumer
  boot:
    admin:
      client:
        #url: "http://localhost:8000"
         url: "http://192.168.2.110:8000"
  zipkin:
    #host: 192.168.2.110
    base-url: http://192.168.2.110:9411/
    #base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#开启熔断器
feign:
  hystrix:
    enabled: true